// This file is generated by Slice Machine. Update with care!

import CodeBlock from './CodeBlock';
import Embed from './Embed';
import Gallery from './Gallery';
import Quote from './Quote';
import RichContent from './RichContent';
import Section from './Section';

export {
	CodeBlock,
	Embed,
	Gallery,
	Quote,
	RichContent,
	Section,
};

export const components = {
	code: CodeBlock,
	embed: Embed,
	gallery: Gallery,
	quote: Quote,
	content: RichContent,
	post: Section,
};
